embind: Add support for `std::nullptr_t`
emscripten-core/emscripten pull request #18661
Opened 2023-02-04 00:08 UTC by tritao

As the title says, this adds support for `std::nullptr_t` types to the Embind. This came up when bootstrapping a pre-existing binding generator test suite to work with Embind target.

Used the sig `vpppDn` where `Dn` is the Itanium C++ mangled encoding, but not really sure about the rest of the letters, and couldn't really find any documentation regarding how these signatures mean. Is this documented anywhere?

2023-02-09 20:34 UTC, JeanChristopheMorinPerso commented
I think the first character in the signature represents the return type, in this case `v` is `void` and the rest are the types of the arguments, where `p` is for `pointer`.

2023-02-09 22:35 UTC, brendandahl requested changes

2023-02-09 22:35 UTC, brendandahl commented on test/embind/embind_test.cpp
> +std::nullptr_t emval_test_return_nullptr_t() {
Why would a function have a return type of `std::nullptr_t`. I've seen it used for overloading with parameters but not this?

2023-02-09 22:35 UTC, brendandahl commented on src/embind/embind.js
> +  _embind_register_std_nullptr_t__sig: 'vpppDn',
This should be `vpp`.

2023-02-09 22:35 UTC, brendandahl commented on src/embind/embind.js
> +      'toWireType': function (destructors, value) {
I don't think null is a valid wasm type. This should probably be 0.

2023-02-09 22:35 UTC, brendandahl commented on test/embind/embind_test.cpp
> +std::nullptr_t emval_test_return_nullptr_t() {
I also don't see this function bound anywhere. e.g. look at how `emval_test_not` works.

2025-08-05 16:51 UTC, sbc100 commented
Any interest in landing this still?  Or can it be closed?

2025-08-05 19:50 UTC, brendandahl commented
I'll close since we never heard back on this.

2025-08-05 19:50 UTC, closed without merging

2025-08-06 09:27 UTC, tritao commented
Closing is fine.