embind_ts: handle empty enumerators case
emscripten-core/emscripten pull request #20398
Opened 2023-10-05 12:26 UTC by shrinktofit

2023-10-05 17:37 UTC, brendandahl requested changes
Code changes look good, but please add a test case to https://github.com/emscripten-core/emscripten/blob/main/test/other/embind_tsgen.cpp and update the reference file https://github.com/emscripten-core/emscripten/blob/main/test/other/embind_tsgen.d.ts

2023-10-05 17:38 UTC, brendandahl commented on src/embind/embind_ts.js
> +        out.push('never/* No any enumerators */');
`/* No any enumerators */` = `/* Empty Enumerator */`

2023-10-07 05:36 UTC, shrinktofit commented on src/embind/embind_ts.js
> +        out.push('never/* No any enumerators */');
fbe88e66a527c3a4531f0c3695ec9dc06a56b7f8

2023-10-07 05:36 UTC, shrinktofit commented
> Code changes look good, but please add a test case to https://github.com/emscripten-core/emscripten/blob/main/test/other/embind_tsgen.cpp and update the reference file https://github.com/emscripten-core/emscripten/blob/main/test/other/embind_tsgen.d.ts

Done here: https://github.com/emscripten-core/emscripten/pull/20398/commits/c6010b25680590c6e3fff12675918460a94547ee

2023-10-07 13:24 UTC, shrinktofit commented
I have no idea why CI failed @brendandahl

2023-10-10 10:34 UTC, brendandahl commented
It was probably just some flakyiness in the test harness.

2023-10-10 12:51 UTC, brendandahl approved these changes
Thanks!

2023-10-10 12:51 UTC, merged