[embind] Minor refactor to use more modern JS features
emscripten-core/emscripten pull request #21331
Opened 2024-02-13 18:29 UTC by sbc100

2024-02-13 21:42 UTC, brendandahl requested changes

2024-02-13 21:42 UTC, brendandahl commented on src/embind/embind_shared.js
> +          invokerFnBody += `${paramName}_dtor${paramName});\n`;
Looks like a paren was dropped here.

2024-02-14 06:47 UTC, sbc100 commented on src/embind/embind_shared.js
> +          invokerFnBody += `${paramName}_dtor${paramName});\n`;
Oops, good catch

2024-02-14 22:23 UTC, brendandahl approved these changes
r+ with the tests passing (hopefully last comment fixes them)

2024-02-14 22:23 UTC, brendandahl commented on src/embind/embind_shared.js
> +    invokerFnBody += "return " + (isAsync ? "rv.then(onDone)" : `onDone(${returnVal})` + ";";
Looks like another `)` was dropped here.

2024-02-15 00:40 UTC, merged